[package]
name = "sealantern-feature"
version.workspace = true
edition.workspace = true
license = "GPL-3.0-only"

[lib]
path = "src/lib.rs"

[features]
default = []
online-tunnel = ["dep:sculk"]

[dependencies]
sealantern-contract = { path = "../contract" }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
cron = "0.12"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "fs", "sync", "time"] }
urlencoding = "2"
uuid = { version = "1", features = ["v4"] }
thiserror = "1"
tempfile = "3"
sealantern-core = { path = "../core" }
sealantern-infra = { path = "../infra" }
rusqlite = { version = "0.32", features = ["bundled"] }
regex = "1"
sha2 = "0.10"
reqwest = { version = "0.12", features = ["json", "stream"] }
dirs = "5"
dom_query = "0.27"
mlua = { version = "0.10", features = ["lua54", "vendored", "serialize", "send"] }
sculk = { version = "=0.3.1", default-features = false, optional = true }
java-manager = { path = "../vendor/java-manager" }

[dev-dependencies]
flate2 = "1"
proptest = "1"
tempfile = "3"
